language: node_js
node_js:
  - "4.1"
  - "0.10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mongodb-server mongodb-clients mongodb-dev grunt grunt-cli
install:
  - npm install
  