AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: parts backend function (reads from DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Resources:
  partsEndpoint:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      FunctionName: parts
      Description: parts backend function (reads from DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Role: arn:aws:iam::692391178777:role/s4e_parts_api_read_function_role
      Environment:
        Variables:
          PAGE_SIZE: 12
      Events:
        getCollection:
          Type: Api
          Properties:
            Path: /parts
            Method: GET
        getSingular:
          Type: Api
          Properties:
            Path: /parts/{key}
            Method: GET
Outputs:
    partsApi:
      Description: "API Gateway endpoint URL for Prod stage for parts function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
