AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: entities backend function (reads from DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
Resources:
  partsEndpoint:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      FunctionName: entities
      Description: entities backend function (reads from DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Role: [ ROLE_ARN ]
      Environment:
        Variables:
          PAGE_SIZE: 12
      Events:
        getCollection:
          Type: Api
          Properties:
            Path: /entities/{entity}
            Method: GET
        getSingular:
          Type: Api
          Properties:
            Path: /entities/{entity}/{id}
            Method: GET
Outputs:
    partsApi:
      Description: "API Gateway endpoint URL for Prod stage for entities function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
